### ISSUE TITLE
Migrate admin lookup config to a global setting

### ISSUE THREAD

**Issue by missinglink** [pelias/admin-lookup#19] opened 2015-06-27 10:08 UTC
Having per-import settings for enabling/disabling admin-lookups creates a messy/leaky abstraction, eg:

https://github.com/pelias/openstreetmap/blob/master/index.js#L30
https://github.com/pelias/geonames/blob/master/task/import.js#L117

It would be much nicer if this lib was responsible for enabling/disabling itself rather than giving that responsibility to it's caller.

In order to do this easily we will probably need to move to a 'global' setting rather than a per-import setting, however this is not really a problem as I found from using this setting that I've never needed to enable admin-lookup for one import while disabling it for another.

**Comment by dianashk** [comment] 2016-03-07 18:13
We still need to allow each importer to indicate whether or not admin lookup is turned on, or at the very least be able to override it. We definitely should make sure the mechanism for doing so is consistent across all the importers.

**Comment by dianashk** [comment] 2016-03-07 18:15
Closing as a dupe of pelias/pelias#255

**Closed by dianashk** 2016-03-07 18:15 UTC
Labels: enhancement, help wanted
