### ISSUE TITLE
Intersection precision

### ISSUE THREAD

**Issue by missinglink** [pelias/admin-lookup#1] opened 2015-02-19 12:41 UTC
hey @sevko I had a bit of a play with this lib and I found that the `admin1` intersection for a local POI was different from the old intersection code.

This is the place I was looking for:
https://pelias.mapzen.com/reverse?lat=51.531766&lon=-0.066717&size=1

You can see there that the Borough (admin1) is 'Hackney' which is correct, as that is the council responsible for collecting taxes in that area for rubbish collection etc.

The intersection made by `admin-lookup` for that lat/lon geocoded the `admin1` value as the neighbouring Borough of 'Tower Hamlets':

```javascript
{ name: { default: 'hackney city farm' },
  center_point: { lon: -0.066717, lat: 51.531766 },
  admin0: 'United Kingdom',
  admin1: 'Tower Hamlets',
  alpha3: 'GBR',
  locality: 'London',
  neighborhood: 'Haggerston' }
```

I'm not sure what's going on here but it seems like the ES intersections were more accurate in this case?

This is a screencap of the `admin1` quattro layer centered on that lat/lon:

![screenshot](http://peter.johnson.s3.amazonaws.com/hackney-tower-hamlets.png)

**Comment by missinglink** [comment] 2015-02-19 12:51
I just tested another one for the NYC office and there were also some differences (missing local_admin):

https://pelias.mapzen.com/reverse?lon=-73.9903421&lat=40.7442434

```javascript
{ name: { default: 'accelerator' },
  center_point: { lon: -73.990342, lat: 40.744243 },
  admin0: 'United States',
  admin1: 'New York',
  alpha3: 'USA',
  admin2: 'New York',
  locality: 'New York',
  neighborhood: 'Flatiron District' }
```

**Comment by sevko** [comment] 2015-02-19 14:41
Thanks for the bug report! The first issue is due to the fact that the polygons are [simplified](https://github.com/pelias/admin-lookup/blob/master/lib/load_shapefile.js#L76,L91) as they're loaded into memory, because otherwise they exceed Node's heap limit and everything freezes up (we're brushing up against Node limitations, again). Note that this is in addition to the simplification we already perform during our Quattroshapes pre-processing step. See the following image, where blue lines are simplified and red lines are *not* simplified, and the black point is the one you searched for:

![imprecision](https://cloud.githubusercontent.com/assets/4467604/6268428/c554763e-b81a-11e4-973e-f67bf9916c81.png)

While it's inside the unsimplified Hackney polygon, it only falls inside the simplified Tower Hamlets one. I'm pretty sure that I can remove the need for simplification with some clever manual compression, because, if I recall correctly, most of the heap usage is due to the large number of arrays in GeoJSON, but I'll need to investigate. The second issue is sheer programmer error... I'm setting `Document`s' `localadmin` values, and not `local_admin`.

**Comment by sevko** [comment] 2015-02-19 15:27
I used [node-memwatch](https://github.com/lloyd/node-memwatch) to get some heap usage snapshots. At the current simplification rate, we still end up loading a little over 1gb of data into memory, with the following types occupying the most:

type | usage
--- | ---
Array | 715mb
Number | 256mb
Object | 51mb
String | 39mb

Looks like `Array`s are the biggest problem, which isn't a surprise because GeoJSON uses one per point. Note how much more space they take up than the actual `Number` coordinates. Here's the snapshot:

```
{
	"before": {
		"nodes": 26132,
		"time": "2015-02-19T15:11:31.000Z",
		"size_bytes": 3499128,
		"size": "3.34 mb"
	},
	"after": {
		"nodes": 39456764,
		"time": "2015-02-19T15:16:46.000Z",
		"size_bytes": 1122725016,
		"size": "1070.71 mb"
	},
	"change": {
		"size_bytes": 1119225888,
		"size": "1067.38 mb",
		"freed_nodes": 1160,
		"allocated_nodes": 39431792,
		"details": [
			{
				"what": "Arguments",
				"size_bytes": 200,
				"size": "200 bytes",
				"+": 5,
				"-": 0
			},
			{
				"what": "Array",
				"size_bytes": 749973352,
				"size": "715.23 mb",
				"+": 20786141,
				"-": 499
			},
			{
				"what": "Buffer",
				"size_bytes": 96,
				"size": "96 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "Closure",
				"size_bytes": 4824,
				"size": "4.71 kb",
				"+": 73,
				"-": 6
			},
			{
				"what": "Code",
				"size_bytes": 486256,
				"size": "474.86 kb",
				"+": 1209,
				"-": 292
			},
			{
				"what": "Config",
				"size_bytes": -104,
				"size": "-104 bytes",
				"+": 0,
				"-": 1
			},
			{
				"what": "DestroyableTransform",
				"size_bytes": 192,
				"size": "192 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "Native",
				"size_bytes": 4235264,
				"size": "4.04 mb",
				"+": 2,
				"-": 0
			},
			{
				"what": "Number",
				"size_bytes": 269189888,
				"size": "256.72 mb",
				"+": 16824368,
				"-": 0
			},
			{
				"what": "Object",
				"size_bytes": 53589416,
				"size": "51.11 mb",
				"+": 1358573,
				"-": 10
			},
			{
				"what": "PolygonLookup",
				"size_bytes": 520,
				"size": "520 bytes",
				"+": 5,
				"-": 0
			},
			{
				"what": "ReadableState",
				"size_bytes": 1144,
				"size": "1.12 kb",
				"+": 5,
				"-": 0
			},
			{
				"what": "RegExp",
				"size_bytes": 72,
				"size": "72 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "ShapeFileStream",
				"size_bytes": 96,
				"size": "96 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "SlowBuffer",
				"size_bytes": 64,
				"size": "64 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "String",
				"size_bytes": 41751368,
				"size": "39.82 mb",
				"+": 460448,
				"-": 45
			},
			{
				"what": "TTY",
				"size_bytes": 32,
				"size": "32 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "TransformState",
				"size_bytes": 280,
				"size": "280 bytes",
				"+": 3,
				"-": 0
			},
			{
				"what": "WritableState",
				"size_bytes": 720,
				"size": "720 bytes",
				"+": 4,
				"-": 0
			},
			{
				"what": "WriteStream",
				"size_bytes": 104,
				"size": "104 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "get",
				"size_bytes": 24,
				"size": "24 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "rbush",
				"size_bytes": 520,
				"size": "520 bytes",
				"+": 5,
				"-": 0
			},
			{
				"what": "set",
				"size_bytes": 24,
				"size": "24 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "slice",
				"size_bytes": 48,
				"size": "48 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "subarray",
				"size_bytes": 24,
				"size": "24 bytes",
				"+": 1,
				"-": 0
			}
		]
	}
}
```

**Comment by sevko** [comment] 2015-02-19 16:06
Indeed. Flattening GeoJSON's nested `geometry.coordinates` arrays to a single array, or:

```
[[
    [1, 2],
    [3, 4],
    [5, 6]
]]
```

to

```javascript
[1, 2, 3, 4, 5, 6]
```

reduced `Array` memory consumption from 715mb to 405mb (see below for the full snapshot). So, this is an inherent architectural problem with `admin-lookup`. Node breaks down past ~1gb of memory usage, meaning that we can only load so many polygons into memory. With simplification, Quattroshapes (sans `admin0`) just squeaks by, but without it, not so much. If we add OSM polygons into the mix ( @dianashk ), it'll be hopeless. @missinglink , we'll need to discuss how we want to resolve this problem.

`admin-lookup` is significantly faster and more accurate than the elasticsearch lookup -- the problem you reported was just due to additional simplification to fit into memory -- so it still seems like the obvious way forward. We'll need to figure out how to reduce/get around its memory footprint if we want to keep using it, though. Two ideas off the top of my head:

  1. manually compressing the polygon data, like I did above by flattening GeoJSON coordinates. Of course, this'll require taking an existing `point-in-polygon` library and modifying it such that it works on a flat array, rather than an array of 2D point arrays. IMO, ugly hack, totally not scalable.
  2. writing native bindings, and shoving this lookup into the C++ side, where it'll be both faster and memory won't be an issue. Now that @dianashk 's on-board, something like that is more achievable.

### second snapshot
```javascript
{
	"before": {
		"nodes": 26114,
		"time": "2015-02-19T15:53:49.000Z",
		"size_bytes": 3495216,
		"size": "3.33 mb"
	},
	"after": {
		"nodes": 24603702,
		"time": "2015-02-19T15:56:58.000Z",
		"size_bytes": 786581088,
		"size": "750.14 mb"
	},
	"change": {
		"size_bytes": 783085872,
		"size": "746.81 mb",
		"freed_nodes": 1177,
		"allocated_nodes": 24578765,
		"details": [
			{
				"what": "Arguments",
				"size_bytes": 120,
				"size": "120 bytes",
				"+": 3,
				"-": 0
			},
			{
				"what": "Array",
				"size_bytes": 425703032,
				"size": "405.98 mb",
				"+": 6676165,
				"-": 534
			},
			{
				"what": "Buffer",
				"size_bytes": 96,
				"size": "96 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "Closure",
				"size_bytes": 4824,
				"size": "4.71 kb",
				"+": 73,
				"-": 6
			},
			{
				"what": "Code",
				"size_bytes": 480496,
				"size": "469.23 kb",
				"+": 1203,
				"-": 285
			},
			{
				"what": "Config",
				"size_bytes": -104,
				"size": "-104 bytes",
				"+": 0,
				"-": 1
			},
			{
				"what": "DestroyableTransform",
				"size_bytes": 192,
				"size": "192 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "Native",
				"size_bytes": 4235264,
				"size": "4.04 mb",
				"+": 2,
				"-": 0
			},
			{
				"what": "Number",
				"size_bytes": 257301888,
				"size": "245.38 mb",
				"+": 16081368,
				"-": 0
			},
			{
				"what": "Object",
				"size_bytes": 53588376,
				"size": "51.11 mb",
				"+": 1358545,
				"-": 13
			},
			{
				"what": "PolygonLookup",
				"size_bytes": 520,
				"size": "520 bytes",
				"+": 5,
				"-": 0
			},
			{
				"what": "ReadableState",
				"size_bytes": 1144,
				"size": "1.12 kb",
				"+": 5,
				"-": 0
			},
			{
				"what": "RegExp",
				"size_bytes": 72,
				"size": "72 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "ShapeFileStream",
				"size_bytes": 96,
				"size": "96 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "SlowBuffer",
				"size_bytes": 64,
				"size": "64 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "String",
				"size_bytes": 41757592,
				"size": "39.82 mb",
				"+": 460441,
				"-": 31
			},
			{
				"what": "TTY",
				"size_bytes": 32,
				"size": "32 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "TransformState",
				"size_bytes": 280,
				"size": "280 bytes",
				"+": 3,
				"-": 0
			},
			{
				"what": "WritableState",
				"size_bytes": 720,
				"size": "720 bytes",
				"+": 4,
				"-": 0
			},
			{
				"what": "WriteStream",
				"size_bytes": 104,
				"size": "104 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "get",
				"size_bytes": 24,
				"size": "24 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "rbush",
				"size_bytes": 520,
				"size": "520 bytes",
				"+": 5,
				"-": 0
			},
			{
				"what": "set",
				"size_bytes": 24,
				"size": "24 bytes",
				"+": 1,
				"-": 0
			},
			{
				"what": "slice",
				"size_bytes": 48,
				"size": "48 bytes",
				"+": 2,
				"-": 0
			},
			{
				"what": "subarray",
				"size_bytes": 24,
				"size": "24 bytes",
				"+": 1,
				"-": 0
			}
		]
	}
}
```

**Comment by sevko** [comment] 2015-02-19 21:00
Currently working on a multi-process solution that'll allow us to easily load unsimplified Quattroshapes into memory. Then, we'll be able to more effectively test the current `admin-lookup` against the old elasticsearch lookup and ensure that there aren't any regressions.

**Comment by sevko** [comment] 2015-02-25 18:17
Should be resolved in [this PR](https://github.com/pelias/admin-lookup/pull/4).

**Closed by sevko** 2015-02-25 18:17 UTC
