### ISSUE TITLE
missing admin info

### ISSUE THREAD

**Issue by missinglink** [pelias/admin-lookup#24] opened 2015-10-07 18:32 UTC
```
    {
      "type": "Feature",
      "properties": {
        "id": "2099:locality:us:usa:san_francisco",
        "gid": "qs:locality:2099:locality:us:usa:san_francisco",
        "layer": "locality",
        "source": "qs",
        "name": "San Francisco",
        "confidence": 0.944,
        "label": "San Francisco"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.693987433227,
          37.7597174746894
        ]
      }
    },
```

**Comment by dianashk** [comment] 2015-10-13 14:51
Will be fixed with WOF integration.

**Comment by orangejulius** [comment] 2016-01-28 16:54
Closing as dupe of pelias/pelias#156

**Closed by orangejulius** 2016-01-28 16:54 UTC
Labels: on-deck, v1, wof-related
